### ISSUE TITLE
Rails 4.2 and Cells 3

### ISSUE THREAD

**Issue by pwim** [apotonick/cells#257]
To get cells 3.11 working with Rails 4.2, only [a small change is needed](https://github.com/pwim/cells/commit/dd2c58fff9697f634bb6447d6a25df0e56c723f6). Could we get a cells 3.12 for Rails 4.2 compatibility?

**Comment by balauru** [comment]
I still can get to work with rails 4.2, I get:

```
/home/calin/.rvm/gems/ruby-2.1.5@webomni/gems/cells-3.11.3/lib/cell/test_case.rb:145:in `<class:TestCase>': uninitialized constant ActionDispatch::Assertions::SelectorAssertions (NameError)
```

**Comment by seuros** [comment]
If i recall correctly, those selectors are extracted to another gem in 4.2.

**Comment by pwim** [comment]
Try adding the gem `rails-dom-testing`

**Comment by balauru** [comment]
@pwim adding the gem did the trick, still does not look like a permanent solution

**Comment by seuros** [comment]
@balauru : It is.

**Comment by apotonick** [comment]
What if people use Capybara, they don't need the `rails-dom-testing` gem (thanks @pwim for that hint!). Do you _have_ to include that gem when you use `Cell::TestCase` in Rails 4.2?

Cells 4 will soon be ready and doesn't have all this mess anymore, that's why we're not really focusing on a fix here, @balauru ! :beers:
