### ISSUE TITLE
`render :nothing => true` attempts to render normal template

### ISSUE THREAD

**Issue by rhomeister** [apotonick/cells#267]
Using 4.0.0.beta2.

Simple test:

In cell: `render nothing: true`
In template: "hi!"

Result: "hi!"

**Comment by rhomeister** [comment]
OK. Just figured out that `return ''` does the same. However, this could be a little counter-intuitive for other Rails users.

**Comment by apotonick** [comment]
The `nothing: true` is Rails API, Cells tries hard to get away from that! :wink:  I've never liked that particular "signature" since it embraces Rails' monolithic rendering. (I mean, how awkward is it to say `render nothing: true` to do exactly _nothing_, hahaha?)

You can use `return` to return _nothing_. 

```ruby
def show
  do_stuff
  return
end
```

Maybe we should add that to the README/book?

Thanks for pointing it out! :heart:
