### ISSUE TITLE
Overly complex code to use form_helpers?

### ISSUE THREAD

**Issue by samstickland** [apotonick/cells#274]
So after a lot of digging around I found that I need to the following to use bootstrap_form_for's method (which is a builder that uses form_for under the hood)

    class WorkHistoryFormCell < Cell::ViewModel
      include BootstrapForm::Helper
      include ActionView::Helpers::FormHelper

      helper_method :bootstrap_form_for
    
      def dom_class(record, prefix = nil)
        ActionView::RecordIdentifier.dom_class(record, prefix)
      end
    
      def dom_id(record, prefix = nil)
        ActionView::RecordIdentifier.dom_id(record, prefix)
      end
    
      def show
        render
      end
    end

Is this really right? I had to assemble this from various issues posted here. It seems overly complex to me, and none of this is mentioned in the docs.

**Comment by apotonick** [comment]
First of all, you don't need to use `helper_method` since all instance methods of the view model are "helpers" in the view.

Second, I can't help that the Rails helpers and all gems that add helpers are extremely hard to use in a non-AV-conform environment. Helpers automatically assume that all the other helpers are magically there.

This is not my fault, but a Rails design flaw. I am hoping that Cells 4 will gently force Rails core and other helper authors to properly include dependent modules into their helpers. I can't fix ever possible helper in the Rails eco-system myself. Sorry for this inconvenience. :stuck_out_tongue_winking_eye:

**Comment by samstickland** [comment]
Thanks for the reply. I'm going to submit a pull request to update the readme when I get time. It took quite a long time to gather all the required information to make this work! :)
