### ISSUE TITLE
"layout: false" not work

### ISSUE THREAD

**Issue by RainThinks** [apotonick/cells#314]
class MyCell < Cell::ViewModel
      layout :my_layout
      def show
         render
      end
     
      #other cells with layout
      #....

      def cell_without_layout
        #still applied the layout
        render layout: false  #also tried layout: nil
      end
    end

is there anyway to render a cell without layout in a ViewModel which declared a class level layout?

**Comment by apotonick** [comment]
Uhm, I don't think so. That's on purpose because a cell usually has a handful of public, rendering methods, only, so it's safe to declare it "globally" on the class level. If you don't want that, pass the layout when rendering the views that actually need a layout, e.g. `render layout: :default`.

I tried to keep layout logic in Cells as simple as possible. If you look into the Rails code and how they provide 25-30 different ways to compute a layout, you will understand my motivations.

Can you explain your use case a bit more detailed?

**Comment by apotonick** [comment]
One assumption you might have missed is that one cell class only has one public method (`show`), in your example, it looks as if you expose several of those. This is outdated 3.x behavior and not encouraged any more.
