### ISSUE TITLE
Default show/call/to_s/render method

### ISSUE THREAD

**Issue by firedev** [apotonick/cells#324]
Instead of having...
```ruby
def show
  render
end
```
...in each cell I suggest to have...

```ruby
def to_s
  call.html_safe
end
```
... in the super class.

Profits?
1. You don't need to have extra method in your cell. Besides what would the test look like? 
```ruby
specify '#show' do
  expect(subject).to receive(:render)
  subject.show
end
```
2. You don't have inconsistency between `= cell`, `=cell.call` and `=cell.(collection: ...)` that is mentioned in https://github.com/apotonick/cells/issues/305#issuecomment-144010183
3. !!!!

**Comment by apotonick** [comment]
I still don't understand how 

```ruby
def to_s
  call.html_safe
end
```

will save you from having to define a `#show` method, because `to_s` will call `call` which will call `show`, so your actual problem is the "missing" `show` method.

As discussed, this is a design decision I made to avoid confusion for new users who will have trouble understanding that they 

1. can actually override the render process (e.g. with `render :another_template`)
2. can add logic to `#show` (`def show; @bla = Whatever.(); end)
3. can extend the rendering (`render(:item) + render + "hello"`).

You can easily add a `show` method to your "base class". 

```ruby
Cell::Concept.class_eval do
def show; render; end
end
```

Also, the `to_s` method is already aliased to `call`, which, in Rails, will call `show.html_safe`.
