### ISSUE TITLE
API improvement so Cell accepts either model, options or both

### ISSUE THREAD

**Issue by firedev** [apotonick/cells#328]
What about an API improvement so it either requires `model`, `options` or both?

```ruby
def cell(name, model = nil, **options)
  ...
end

cell('test')
=> name:  test, model: nil, options: {}

cell('test', Object)
=> name:  test, model: Object, options: {}

cell('test', admin: true)
=> name:  test, model: nil, options: { admin: true }

cell('test', Object, admin: true)
=> name:  test, model: Object, options: { admin: true }
```

The reason for this – it looks kind of strange when you need to pass hash to fish for values inside the `model` or pass aditional `nil` in that case.

**Comment by apotonick** [comment]
We had that fuzzy API in earlier Cells and it was confusing. Aren't you all about strong, non-blurry APIs? :stuck_out_tongue_winking_eye: The API you suggest is indeed very "railsy".

Also, we want to drive things more towards using twins or structs instead of model/hash mixes, where the twin represents your actual domain object (even if that is a view domain-specific thing). This means, the cell will always get one "model" only and you don't use `@options` anymore.

BTW, I am all-in for incorporating twins/decorators into the language itself. There's no reason we're still messing around with primitive hashes to simulate domain objects. Ruby could support that out-of-the-box and people would think different about what objects they pass around between layers.
