### ISSUE TITLE
Namespace inflector.

### ISSUE THREAD

**Issue by sveredyuk** [apotonick/cells#395]
How cells inflect module/class names ? I think it not using rails inflections which define different types of acronyms ?

**Comment by apotonick** [comment]
No, of course not. Cells doesn't use Rails.

What exactly do you need? Note that you can simply pass the constant directly in 4.1.  https://github.com/apotonick/cells/blob/master/CHANGES.md#410

Here's where the "inflection" is invoked: https://github.com/apotonick/cells/blob/master/lib/cell/view_model.rb#L57

**Comment by tdtadeu** [comment]
It took me some time to figure this out, since it's not an expected behavior; I'd expect cells to use my inflections to calculate cell class names.

I forked the gem to help with the issue using the ``:classify`` method defined in activesupport, is there aything wrong with using rails within a gem specifically designed to support rails apps?

**Comment by samstickland** [comment]
I think passing a string to the cell method is deprecated. You should pass the constant name.

**Comment by saiqulhaq** [comment]
@tdtadeu activesupport dependency should be avoided
because not every app is rails app
and activesupport is not small gem, it's a huge gem
